services:
  legalhelperdb:
    build: 
      context: ../legal-helper-db
      dockerfile: Dockerfile
    container_name: legalhelperdb 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE:      ${DB_NAME}
      MYSQL_USER:          ${DB_USER}
      MYSQL_PASSWORD:      ${DB_PASS}
    env_file:
      - .env 

    ports:
      - "3306:3306"
    volumes:
      - ./legalhelperdb:/var/lib/mysql
    networks:
      - legalhelper-network  

  lh-neo4j:
    image: neo4j:latest
    container_name: lh-neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - legalhelper-network
    volumes:
      - ./lh-neo4j-data:/data
    environment:
      - NEO4J_AUTH=none

  lh-api:
    build: 
      context: ../vietnamese-law-bot
      dockerfile: src/Dockerfile
    image: lh-api
    container_name: lh-api
    restart: unless-stopped
    ports:
      - 8001:8001
    networks:
      - legalhelper-network
    depends_on:
      - lh-neo4j
    env_file:
      - .env
    environment:
      - NEO4J_HOST=lh-neo4j

  legalhelper:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: legalhelper
    restart: always
    depends_on:
      - legalhelperdb
      - lh-api
    ports:
      - "8000:8000"
    networks:
      - legalhelper-network
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS} 
      DB_NAME: ${DB_NAME}
      LAW_RAG_CHAT_URL: ${LAW_RAG_CHAT_URL}
    env_file:
      - .env 

networks:
  legalhelper-network:
    driver: bridge
